In [1]:
## Importing the dependencies
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv

In [3]:
diabetes_dataset = pd.read_csv("diabetes.csv")
print(diabetes_dataset.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1

In [4]:
# no. of rows and columns in this dataset
diabetes_dataset.shape

(768, 9)

In [5]:
#getting the statistical measures of the data frame
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
# 0--> non dibetic
# 1--> dibetic

In [7]:
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [8]:
# seperating the data and labels
x= diabetes_dataset.drop(columns ='Outcome',axis = 1)
y = diabetes_dataset['Outcome']
print(x)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [9]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [10]:
#Data standarization
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [11]:
standardized_data =scaler.transform(x)

In [12]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [13]:
x = standardized_data
y = diabetes_dataset['Outcome']

In [14]:
print(x)
print(y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [24]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    stratify=y,
    random_state=2
)

# Standardize using only the training data
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)

x_train shape: (614, 8)
x_test shape: (154, 8)

In [25]:
from sklearn import svm

classifier = svm.SVC(kernel='linear')
classifier.fit(x_train, y_train)

SVC(kernel='linear')

In [26]:
from sklearn.metrics import accuracy_score

# Training accuracy
x_train_prediction = classifier.predict(x_train)
training_data_accuracy = accuracy_score(y_train, x_train_prediction)

# Testing accuracy
x_test_prediction = classifier.predict(x_test)
test_data_accuracy = accuracy_score(y_test, x_test_prediction)

print("Training Accuracy:", training_data_accuracy)
print("Testing Accuracy:", test_data_accuracy)

Training Accuracy: 0.7866449511400652
Testing Accuracy: 0.7727272727272727

In [27]:
from sklearn.metrics import confusion_matrix, classification_report

# Predictions on test data
y_pred = classifier.predict(x_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[91  9]
 [26 28]]

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.91      0.84       100
           1       0.76      0.52      0.62        54

    accuracy                           0.77       154
   macro avg       0.77      0.71      0.73       154
weighted avg       0.77      0.77      0.76       154

In [28]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=2)

cv_scores = cross_val_score(
    classifier,
    x, y,
    cv=cv,
    scoring='accuracy'
)

print("Cross-validation scores:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())
print("Standard Deviation:", cv_scores.std())

Cross-validation scores: [0.74675325 0.80519481 0.79220779 0.80392157 0.73856209]
Mean CV Accuracy: 0.7773279008573126
Standard Deviation: 0.028784704750554405

In [29]:
import joblib

joblib.dump(classifier, "diabetes_svm_model.pkl")
joblib.dump(scaler, "diabetes_scaler.pkl")

print("Model and scaler saved successfully!")

Model and scaler saved successfully!

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [33]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=2),
    "SVM": svm.SVC(kernel='linear'),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(random_state=2),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=2),
    "Naive Bayes": GaussianNB()
}

print("Models created successfully!")

Models created successfully!

In [34]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=2)

cv_results = {}

for name, model in models.items():
    scores = cross_val_score(
        model,
        x, y,
        cv=cv,
        scoring='accuracy'
    )

    cv_results[name] = {
        "Mean Accuracy": scores.mean(),
        "Std": scores.std()
    }

for name, result in cv_results.items():
    print(
        f"{name}: "
        f"{result['Mean Accuracy']:.4f} ± "
        f"{result['Std']:.4f}"
    )

Logistic Regression: 0.7747 ± 0.0224
SVM: 0.7773 ± 0.0288
KNN: 0.7266 ± 0.0204
Decision Tree: 0.6953 ± 0.0355
Random Forest: 0.7578 ± 0.0210
Naive Bayes: 0.7605 ± 0.0292

In [35]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

test_results = {}

for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    test_results[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred)
    }

for name, result in test_results.items():
    print(f"\n{name}")
    print(f"Accuracy : {result['Accuracy']:.4f}")
    print(f"Precision: {result['Precision']:.4f}")
    print(f"Recall   : {result['Recall']:.4f}")
    print(f"F1-score : {result['F1']:.4f}")

Logistic Regression
Accuracy : 0.7597
Precision: 0.7179
Recall   : 0.5185
F1-score : 0.6022

SVM
Accuracy : 0.7727
Precision: 0.7568
Recall   : 0.5185
F1-score : 0.6154

KNN
Accuracy : 0.7143
Precision: 0.6389
Recall   : 0.4259
F1-score : 0.5111

Decision Tree
Accuracy : 0.7013
Precision: 0.5909
Recall   : 0.4815
F1-score : 0.5306

Random Forest
Accuracy : 0.7208
Precision: 0.6410
Recall   : 0.4630
F1-score : 0.5376

Naive Bayes
Accuracy : 0.7727
Precision: 0.7209
Recall   : 0.5741
F1-score : 0.6392

In [36]:
from sklearn.ensemble import VotingClassifier

svm_model = svm.SVC(
    kernel='linear',
    probability=True,
    random_state=2
)

nb_model = GaussianNB()

voting_model = VotingClassifier(
    estimators=[
        ('svm', svm_model),
        ('nb', nb_model)
    ],
    voting='soft'
)

print("Voting ensemble created successfully!")

Voting ensemble created successfully!

In [37]:
voting_cv_scores = cross_val_score(
    voting_model,
    x, y,
    cv=cv,
    scoring='accuracy'
)

print("Voting Ensemble CV scores:", voting_cv_scores)
print("Mean CV Accuracy:", voting_cv_scores.mean())
print("Standard Deviation:", voting_cv_scores.std())

Voting Ensemble CV scores: [0.73376623 0.78571429 0.76623377 0.80392157 0.74509804]
Mean CV Accuracy: 0.7669467787114845
Standard Deviation: 0.02568337507276834

In [38]:
voting_model.fit(x_train, y_train)

y_pred_voting = voting_model.predict(x_test)

print("Voting Ensemble Test Results")
print("Accuracy :", accuracy_score(y_test, y_pred_voting))
print("Precision:", precision_score(y_test, y_pred_voting))
print("Recall   :", recall_score(y_test, y_pred_voting))
print("F1-score :", f1_score(y_test, y_pred_voting))

Voting Ensemble Test Results
Accuracy : 0.7532467532467533
Precision: 0.7
Recall   : 0.5185185185185185
F1-score : 0.5957446808510638

In [39]:
# Final SVM model
final_model = svm.SVC(kernel='linear')
final_model.fit(x_train, y_train)

# Save final model and scaler
joblib.dump(final_model, "diabetes_svm_model.pkl")
joblib.dump(scaler, "diabetes_scaler.pkl")

print("Final SVM model saved successfully!")

Final SVM model saved successfully!

In [40]:
def diabetes_prediction(input_data):
    input_data = np.asarray(input_data, dtype=float)
    input_data = input_data.reshape(1, -1)

    # Standardize using the scaler fitted on training data
    input_data = scaler.transform(input_data)

    prediction = final_model.predict(input_data)

    if prediction[0] == 0:
        return "The person is not diabetic"
    else:
        return "The person is diabetic"

In [41]:
sample_input = [6, 148, 72, 35, 0, 33.6, 0.627, 50]

result = diabetes_prediction(sample_input)
print(result)

The person is diabetic